version: '3'

services:
  database-fitbud:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=dbfitbud
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpwd
      - MYSQL_ROOT_PASSWORD=mypass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      - database-fitbud
    environment:
      - APP_ENV=dev
      - APP_SECRET=19fe1f9a37a64f57277cea71d3a48328
      - DATABASE_URL=mysql://dbuser:dbpwd@database-fitbud:3306/dbfitbud?serverVersion=5.7
    volumes:
      - ../:/var/www

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"


volumes:
  db_data: